### PR TITLE
Pg/blas memory

### PR DESCRIPTION
**Pull request by goulart-paul**
Implements memory efficient PSD projection using BLAS

### CODE REVIEW

**Comment by goulart-paul** [comment]
@migarstka Travis CI fails because I used UnsafeArrays, which is not currently in our list of dependencies.   Probably best if you see if you are happy with the changes first before updating it.

**Comment by migarstka** [comment]
I added it the dependency to this branch for now.

**Comment by migarstka** [comment]
One thing I don't understand is why the symmetry-enforcing line 
https://github.com/oxfordcontrol/COSMO.jl/blob/159b435d5ab2e4ab1fefad6d9b0cc5efde7bbf42/src/convexset.jl#L255
before the projection is necessary, as `_syevr!()`uses only the upper-triangle anyway.

When I compare the projection step without this line to the previous code I get different results after the projection.

**Comment by goulart-paul** [comment]
I think it can only be because the matrix `X` is not symmetric before the projection.   I think projecting a general (non-symmetric ) matrix onto SD code is the same as projecting its symmetric part onto the same cone.

It's not clear to me why X should not be symmetric in the first place, but I guess that it is not enforced anywhere in the linear constraints.

**Comment by migarstka** [comment]
I replaced the rank-1 update with a rank-k update which is faster.

**Pull request merged**
