### PR TITLE
Covering more cases in CI

### PR DESCRIPTION
**Pull request by matbesancon**
CI only runs on ubuntu and 64-bits architectures.
This caused some uncovered failures downstream (https://github.com/jump-dev/MatrixOptInterface.jl/pull/13) because of the Int64-specific code.

It was basically replacing Int64 -> Int everywhere
Corrected that and fixed a warning in the test

### CODE REVIEW

**Comment by matbesancon** [comment]
There are definitely more subtle bugs uncovered by this. Up to the maintainers whether you want this covered or not. Overall it's not a good idea to over-constrain your methods when not for dispatch

**Comment by migarstka** [comment]
Thanks for flagging this. I'll add a 32-bit architecture to the CI.

**Comment by matbesancon** [comment]
Do you want to go with this PR or should I close it?

**Comment by migarstka** [comment]
Thanks. 

I merged it and will add a few more changes on `mg/fix_int`.

**Pull request merged**
