### PR TITLE
Fix slow MOI merging step

### PR DESCRIPTION
**Pull request by migarstka**
- The current way I merge k COSMO.Nonnegatives(1) into one COSMO.Nonnegatives(k)
is extremely slow
- This fix also removes constraint support for the scalar sets as that should
be handled by MOI.Bridges
- 1 MOI unit test still errors

### CODE REVIEW

**Comment by migarstka** [comment]
@blegat One of the MOI unit tests errors. But I don't understand what's going on. It seems to happen when the constraint in `linear14` is deleted. With this error message:
```
The index MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Interval{Float64}}(3) is invalid. Note that an index becomes invalid after it has been deleted.linear14: Error During Test at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Test/config.jl:47
  Got exception outside of a @test

  Stacktrace:
   [1] throw_if_not_valid at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/indextypes.jl:75 [inlined]
   [2] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Interval{Float64}}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:410
   [3] delete at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Constraint/set_map.jl:38 [inlined]
   [4] #16 at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:419 [inlined]
   [5] call_in_context(::MathOptInterface.Bridges.Variable.Map, ::Int64, ::MathOptInterface.Bridges.var"#16#17"{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}},MathOptInterface.Bridges.Constraint.LessToIntervalBridge{Float64,MathOptInterface.SingleVariable}}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Variable/map.jl:404
   [6] call_in_context(::MathOptInterface.Bridges.Variable.Map, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}, ::Function) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Variable/map.jl:435
   [7] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:419
   [8] _delete_variables_in_variables_constraints(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::Array{MathOptInterface.VariableIndex,1}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:350
   [9] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::Array{MathOptInterface.VariableIndex,1}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:356
   [10] linear14test(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.Test.TestConfig{Float64}) at /Users/Micha/.julia/packages/MathOptInterface/ZJFKw/src/Test/contlinear.jl:1653
```

I guess it's related to the fact that I removed direct support for some constraints:
https://github.com/oxfordcontrol/COSMO.jl/blob/142fcfd0e940627c3e126d109eee90794d89e635/src/MOIWrapper.jl#L788-L789

**Comment by odow** [comment]
I would go though the test line by line: https://github.com/jump-dev/MathOptInterface.jl/blob/8d8beb387551d45138857bd472328718ba98ca8e/src/Test/contlinear.jl#L2313-L2476

The error occurs when multiple variables are deleted: https://github.com/jump-dev/MathOptInterface.jl/blob/162049e15415b47a40c29d9a0aa9d6acf58a2d72/src/Test/contlinear.jl#L1653

**Comment by migarstka** [comment]
So COSMO supports `VectorAffineFunction` + `vectorsets` and `ScalarAffineFunction` + `Interval`.
The problem has a couple of one-sided scalar inequality constraints which get bridged to `MOI.Interval`. Then when one of the constraints gets deleted, I assume MOI tries to turn the `Interval` constraint into a `SingleVariable`-in-`LessThan` or `GreaterThan` which might cause the error. Shouldn't MOI try to change the constraint to 1d- `VectoAffineFunction`-in- `Nonnegatives`?

**Comment by blegat** [comment]
> I know this is a super-edge-case. I still think a multi-dimensional `Interval` constraint set in MOI would be nice

Would the box constraint support infinite bounds (related to https://github.com/jump-dev/MathOptInterface.jl/pull/1228) ? I'm also in favor of having one `Box` constraint in MOI.

> The problem has a couple of one-sided scalar inequality constraints which get bridged to `MOI.Interval`

I don't think that's possible, each of them are bridged to a separate `Interval` constraint.

> Shouldn't MOI try to change the constraint to 1d- VectoAffineFunction-in- Nonnegatives, i.e. something that the optimizer supports?

You can check what happens with `MOI.Bridges.print_graph`, can you print the output ?

**Comment by migarstka** [comment]
Infinite bounds wouldn't be a problem for us. The box would just effectively be a Nonnegatives/Nonpositives.


This is before `MOI.delete` is called.
```
julia> MOI.Bridges.print_graph(model)
Bridge graph with 1 variable nodes, 5 constraint nodes and 0 objective nodes.
 [1] constrained variables in `MOI.Nonpositives` are bridged (distance 1) by MOIB.Variable.NonposToNonnegBridge{Float64}.
 (1) `MOI.SingleVariable`-in-`MOI.GreaterThan{Float64}` constraints are bridged (distance 1) by MOIB.Constraint.GreaterToLessBridge{Float64,MOI.ScalarAffineFunction{Float64},MOI.SingleVariable}.
 (2) `MOI.SingleVariable`-in-`MOI.Interval{Float64}` constraints are bridged (distance 1) by MOIB.Constraint.ScalarFunctionizeBridge{Float64,MOI.Interval{Float64}}.
 (3) `MOI.SingleVariable`-in-`MOI.LessThan{Float64}` constraints are bridged (distance 1) by MOIB.Constraint.LessToGreaterBridge{Float64,MOI.ScalarAffineFunction{Float64},MOI.SingleVariable}.
 (4) `MOI.VectorAffineFunction{Float64}`-in-`MOI.Nonpositives` constraints are bridged (distance 1) by MOIB.Constraint.NonposToNonnegBridge{Float64,MOI.VectorAffineFunction{Float64},MOI.VectorAffineFunction{Float64}}.
 (5) `MOI.VectorOfVariables`-in-`MOI.Nonpositives` constraints are bridged (distance 1) by MOIB.Constraint.NonposToNonnegBridge{Float64,MOI.VectorAffineFunction{Float64},MOI.VectorOfVariables}.
```

**Comment by blegat** [comment]
I can reduce it to
```julia
model = MOI.instantiate(COSMO.Optimizer, with_bridge_type=Float64)
MOI.empty!(model)
x = MOI.add_variable(model)
c = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.LessThan(1.0))
MOI.delete(model, x)
```
and with debug
```julia
model = MOI.instantiate(COSMO.Optimizer, with_bridge_type=Float64)
MOI.empty!(model)
x = MOI.add_variable(model)
c = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.LessThan(1.0))
b = MOI.Bridges.bridge(model, c)
@show typeof(b)
@show b.constraint
b2 = MOI.Bridges.bridge(model, b.constraint)
@show typeof(b2)
@show b2.constraint
@show MOI.Bridges.is_bridged(model, b2.constraint)
MOI.delete(model, x)
```
which gives
```
typeof(b) = MathOptInterface.Bridges.Constraint.LessToIntervalBridge{Float64,MathOptInterface.SingleVariable}
b.constraint = MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Interval{Float64}}(1)
typeof(b2) = MathOptInterface.Bridges.Constraint.ScalarFunctionizeBridge{Float64,MathOptInterface.Interval{Float64}}
b2.constraint = MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.Interval{Float64}}(1)
MOI.Bridges.is_bridged(model, b2.constraint) = false
ERROR: LoadError: The index MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Interval{Float64}}(1) is invalid. Note that an index becomes invalid after it has been deleted.
Stacktrace:
 [1] throw_if_not_valid at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/indextypes.jl:75 [inlined]
 [2] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Interval{Float64}}) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:410
 [3] delete at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Constraint/set_map.jl:38 [inlined]
 [4] #16 at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:419 [inlined]
 [5] call_in_context(::MathOptInterface.Bridges.Variable.Map, ::Int64, ::MathOptInterface.Bridges.var"#16#17"{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}},MathOptInterface.Bridges.Constraint.LessToIntervalBridge{Float64,MathOptInterface.SingleVariable}}) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Variable/map.jl:404
 [6] call_in_context(::MathOptInterface.Bridges.Variable.Map, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}, ::Function) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Variable/map.jl:435
 [7] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:419
 [8] _delete_variables_in_variables_constraints(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::Array{MathOptInterface.VariableIndex,1}) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:350
 [9] delete(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.VariableIndex) at /home/blegat/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:383
 [10] top-level scope at /home/blegat/.julia/dev/COSMO/tmp.jl:12
 [11] include(::String) at ./client.jl:457
 [12] top-level scope at REPL[50]:1
in expression starting at /home/blegat/.julia/dev/COSMO/tmp.jl:12
```

**Comment by blegat** [comment]
This is an MOI bug, I've opened an issue there.

**Pull request merged**
