### PR TITLE
Add precompile statements

### PR DESCRIPTION
**Pull request by ericphanson**
Closes https://github.com/oxfordcontrol/COSMO.jl/issues/108; see https://gist.github.com/ericphanson/959210a4c44900f2f379a805a0aa3d7c for how these were generated.

### CODE REVIEW

**Comment by migarstka** [comment]
Thanks for the PR.
At the moment the unit test fails for Julia v1.0 which i think is related to
https://github.com/timholy/SnoopCompile.jl/issues/46

**Comment by ericphanson** [comment]
Ah, thanks for looking into it. It looks like just one precompile statement has that `Core.var`, so I just pushed a commit removing that one.

**Comment by migarstka** [comment]
It seems that the function `restart_copyto_nonleaf()` doesn't exist in Julia v1.0

**Comment by ericphanson** [comment]
Ok, this time I tested locally on Julia 1.0, so it should work. Sorry for the trouble!

**Pull request merged**
